### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Sigmafye** [lightaime/sgas#16]
I have this problem when I run the code(cnn/train_search.py). If you could help me solve this, I appreciate. It usually apears after some epochs(28 for me)

Traceback (most recent call last):
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/shutil.py", line 444, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/shutil.py", line 442, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000001835000600002bd7'

The info appears many times when I run the code!

**Comment by lightaime** [comment]
Hi @Sigmafye. I think the error occurs when you are trying to delete opened files. Similar issues are found here: https://github.com/tensorpack/tensorpack/issues/644 and https://github.com/fenderglass/Flye/issues/328. Please track if you are running out of storage on your device or so.

**Comment by Sigmafye** [comment]
Hi @lightaime , thinks for your excellent job and instant reply, I've solved that problem. But new problem appears, it confused me a lot when I run the gcn_graph/train_search.py

 File "train_search.py", line 313, in <module>
    main()
  File "train_search.py", line 177, in main
    train_dataset = GeoData.PPI(os.path.join(args.data, 'ppi'), split='train')
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/site-packages/torch_geometric/datasets/ppi.py", line 55, in __init__
    self.data, self.slices = torch.load(self.processed_paths[0])
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/tie.xu/anaconda3/envs/sgas/lib/python3.6/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
ModuleNotFoundError: No module named 'torch_geometric.data.storage'

Thinks!
