### ISSUE TITLE
drop_path

### ISSUE THREAD

**Issue by quqxui** [lightaime/sgas#7]
Hi, when i run main_ppi.py , there are something wrong with drop_path .
`Traceback (most recent call last):
  File "main_ppi.py", line 163, in <module>
    train()
  File "main_ppi.py", line 56, in train
    train_acc, train_obj,class_acc = train_step( model, criterion, optimizer)
  File "main_ppi.py", line 77, in train_step
    logits, logits_aux = model(features,edge_index)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/model.py", line 98, in forward
    s0, s1 = s1, cell(s0, s1, edge_index, self.drop_path_prob)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/model.py", line 42, in forward
    h1 = drop_path(h1, drop_prob)
  File "/content/drive/My Drive/NAS-GCN-SAR/tools/utils.py", line 137, in drop_path
    x.mul_(mask)
RuntimeError: output with shape [46659, 32] doesn't match the broadcast shape [46659, 1, 46659, 32]`

If i assign 0  to` --drop_path_prob` , that work well. 
Can you help me ? Thank you very mach !!

**Comment by lightaime** [comment]
Hi @quqxui. We did not use drop path in our GCN experiments. I guess it is because the shapes here do not match.
https://github.com/lightaime/sgas/blob/7b6d7636249c84e0d4433e1bbe5f398e8c3dc4b3/gcn/utils.py#L130
We would check and extend the drop path for with GCN.

**Comment by guochengqian** [comment]
Hello. @quqxui. Sorry for my late reply. The drop_path function should be different for PPI and ModelNet since their data format are different. Please check our latest code for PPI exp. 
Thank you for pointing it out.

**Comment by quqxui** [comment]
thank you!
